"""Self-contained HTML index over the generated PNGs."""

import html
import os

from . import figures, metrics

_CSS = """
:root{color-scheme:dark;}
body{background:#1a1a2e;color:#e0e0e0;font-family:Menlo,Consolas,monospace;margin:0;}
.wrap{max-width:1280px;margin:0 auto;padding:32px 22px 64px;}
h1{margin:0 0 6px;font-size:26px;}
.sub{color:#9aa5b1;margin:0 0 6px;}
.meta{color:#6b7785;margin:0 0 26px;font-size:13px;}
.stats{display:flex;flex-wrap:wrap;gap:10px;margin:0 0 26px;}
.stat{background:#16213e;border:1px solid #2a2a4a;border-radius:8px;padding:10px 14px;min-width:104px;}
.stat .k{color:#6b7785;font-size:11px;text-transform:uppercase;letter-spacing:.06em;}
.stat .v{font-size:19px;font-weight:700;margin-top:3px;}
nav{position:sticky;top:0;background:#1a1a2e;padding:12px 0;border-bottom:1px solid #2a2a4a;
    margin:0 0 24px;z-index:5;}
nav a{color:#3498db;margin-right:16px;text-decoration:none;font-size:13px;}
nav a:hover{text-decoration:underline;}
h2.sec{font-size:14px;color:#6b7785;text-transform:uppercase;letter-spacing:.12em;
       margin:36px 0 14px;border-bottom:1px solid #2a2a4a;padding-bottom:8px;}
.card{background:#16213e;border:1px solid #2a2a4a;border-radius:10px;padding:16px;margin:0 0 22px;}
.card h3{margin:0 0 4px;font-size:16px;}
.card .cap{color:#9aa5b1;font-size:13px;margin:0 0 12px;}
img{max-width:100%;height:auto;border-radius:6px;display:block;}
footer{color:#6b7785;font-size:12px;margin-top:40px;}
@media (max-width:640px){.wrap{padding:20px 12px 40px;}}
"""


def _stat_tiles(ov):
    if not ov:
        return ""
    tiles = [
        ("Pitches", f"{ov['pitches']:,}"),
        ("PA", f"{ov['pa']:,}"),
        ("CSW%", f"{ov['csw_pct']:.1f}"),
        ("Whiff%", f"{ov['whiff_pct']:.1f}"),
        ("Chase%", f"{ov['chase_pct']:.1f}"),
        ("K%", f"{ov['k_pct']:.1f}"),
        ("BB%", f"{ov['bb_pct']:.1f}"),
        ("AVG", metrics.fmt_avg(ov["avg"])),
        ("wOBA", metrics.fmt_avg(ov["woba"])),
    ]
    body = "".join(
        f"<div class='stat'><div class='k'>{html.escape(k)}</div>"
        f"<div class='v'>{html.escape(v)}</div></div>" for k, v in tiles)
    return f"<div class='stats'>{body}</div>"


def write(ctx, rendered):
    """Build report.html for the figures that actually got rendered."""
    out_dir = ctx.ensure_out_dir()
    present = [f for f in rendered if os.path.exists(os.path.join(out_dir, f.filename))]
    ov = metrics.overview(ctx)

    span = ctx.date_span
    span_txt = ""
    if span:
        span_txt = (f"{span[0]:%Y-%m-%d} → {span[1]:%Y-%m-%d} · "
                    f"{ov.get('days', 0)} days with pitches")

    parts = [
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>",
        "<meta name='viewport' content='width=device-width,initial-scale=1'>",
        "<title>StrikeFactor — Pitch Analysis</title>",
        f"<style>{_CSS}</style></head><body><div class='wrap'>",
        "<h1>StrikeFactor — Pitch Analysis</h1>",
        f"<p class='sub'>{html.escape(ctx.label)}</p>",
        f"<p class='meta'>{html.escape(span_txt)}</p>",
        _stat_tiles(ov),
    ]

    sections = [s for s in figures.SECTIONS if any(f.section == s for f in present)]
    parts.append("<nav>" + " ".join(
        f"<a href='#{s}'>{html.escape(figures.SECTION_TITLES[s])}</a>"
        for s in sections) + "</nav>")

    for section in sections:
        parts.append(f"<h2 class='sec' id='{section}'>"
                     f"{html.escape(figures.SECTION_TITLES[section])}</h2>")
        for f in [f for f in present if f.section == section]:
            parts.append(
                f"<div class='card'><h3>{html.escape(f.title)}</h3>"
                f"<p class='cap'>{html.escape(f.caption)}</p>"
                f"<img src='{html.escape(f.filename)}' alt='{html.escape(f.title)}'>"
                f"</div>")

    parts.append(
        "<footer>Generated by pitch_analysis.py · "
        "whiff = swing with no contact (outcome strike/strikeout) · "
        "run values are relative within this slice</footer>")
    parts.append("</div></body></html>")

    path = os.path.join(out_dir, "report.html")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("".join(parts))
    return path
